CREATE TABLE "admin_users" (
	"id" serial PRIMARY KEY NOT NULL,
	"username" text NOT NULL,
	"email" text NOT NULL,
	"password_hash" text NOT NULL,
	"role" text DEFAULT 'admin' NOT NULL,
	"is_active" boolean DEFAULT true,
	"first_name" text,
	"last_name" text,
	"avatar" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	"last_login_at" timestamp,
	CONSTRAINT "admin_users_username_unique" UNIQUE("username"),
	CONSTRAINT "admin_users_email_unique" UNIQUE("email")
);
--> statement-breakpoint
CREATE TABLE "client_requests" (
	"id" serial PRIMARY KEY NOT NULL,
	"business_name" text NOT NULL,
	"contact_name" text NOT NULL,
	"email" text NOT NULL,
	"phone" text,
	"company" text,
	"industry" text,
	"business_description" text,
	"years_in_business" text,
	"company_size" text,
	"has_current_website" boolean DEFAULT false,
	"current_website_url" text,
	"current_site_working" text,
	"current_site_not_working" text,
	"reason_for_new_website" text,
	"primary_goal" text,
	"desired_actions" jsonb,
	"success_metrics" jsonb,
	"target_audience" text,
	"age_range" jsonb,
	"geographic_location" text,
	"problems_solved" text,
	"has_customer_personas" boolean DEFAULT false,
	"website_type" text,
	"essential_features" jsonb,
	"number_of_pages" text,
	"content_ready" text,
	"provides_photos" text,
	"preferred_structure" text,
	"design_style" jsonb,
	"color_preferences" text,
	"websites_liked" text,
	"websites_disliked" text,
	"logo_status" text,
	"mobile_responsive" boolean DEFAULT true,
	"seo_optimization" boolean DEFAULT false,
	"analytics_tracking" boolean DEFAULT false,
	"third_party_integrations" jsonb,
	"hosting_preference" text,
	"budget_range" text,
	"desired_launch_date" timestamp,
	"timeline_flexibility" text,
	"ongoing_maintenance" boolean DEFAULT false,
	"main_competitors" text,
	"differentiators" text,
	"competitive_advantages" text,
	"current_lead_generation" jsonb,
	"marketing_goals" jsonb,
	"accessibility_requirements" text,
	"compliance_needs" text,
	"preferred_communication" text,
	"decision_makers" text,
	"special_requirements" text,
	"questions_for_us" text,
	"how_did_you_hear" text,
	"status" text DEFAULT 'new_request' NOT NULL,
	"priority" text DEFAULT 'medium',
	"assigned_to" text,
	"estimated_value" integer,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "communications" (
	"id" serial PRIMARY KEY NOT NULL,
	"request_id" integer NOT NULL,
	"admin_id" integer,
	"type" text NOT NULL,
	"subject" text,
	"message" text NOT NULL,
	"direction" text NOT NULL,
	"email_to" text,
	"email_from" text,
	"email_cc" text,
	"email_bcc" text,
	"status" text DEFAULT 'sent',
	"is_internal" boolean DEFAULT false,
	"attachments" jsonb,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"scheduled_at" timestamp
);
--> statement-breakpoint
CREATE TABLE "status_history" (
	"id" serial PRIMARY KEY NOT NULL,
	"request_id" integer NOT NULL,
	"admin_id" integer,
	"from_status" text,
	"to_status" text NOT NULL,
	"reason" text,
	"notes" text,
	"created_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "templates" (
	"id" serial PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"description" text,
	"category" text NOT NULL,
	"subcategory" text,
	"preview_image" text,
	"thumbnail_image" text,
	"demo_url" text,
	"screenshots" jsonb,
	"is_premium" boolean DEFAULT false,
	"price" integer DEFAULT 0,
	"is_active" boolean DEFAULT true,
	"features" jsonb,
	"tags" jsonb,
	"difficulty" text,
	"wordpress_version" text,
	"required_plugins" jsonb,
	"included_pages" jsonb,
	"download_count" integer DEFAULT 0,
	"rating" integer DEFAULT 0,
	"review_count" integer DEFAULT 0,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "communications" ADD CONSTRAINT "communications_request_id_client_requests_id_fk" FOREIGN KEY ("request_id") REFERENCES "public"."client_requests"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "communications" ADD CONSTRAINT "communications_admin_id_admin_users_id_fk" FOREIGN KEY ("admin_id") REFERENCES "public"."admin_users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "status_history" ADD CONSTRAINT "status_history_request_id_client_requests_id_fk" FOREIGN KEY ("request_id") REFERENCES "public"."client_requests"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "status_history" ADD CONSTRAINT "status_history_admin_id_admin_users_id_fk" FOREIGN KEY ("admin_id") REFERENCES "public"."admin_users"("id") ON DELETE no action ON UPDATE no action;